version: "3.9"

services:
  app:
    container_name: bun-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_URL=postgresql://postgres:root@localhost:5432/opm
      - PORT=3000
      - PUSHER_APP_ID=2060574
      - PUSHER_KEY=12606158d58a465c4cf1
      - PUSHER_SECRET=e88591b8885f2271444c
      - PUSHER_CLUSTER=ap1
      - JWT_SECRET_KEY=kelasdeck
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped