version: "3.9"

services:
  app:
    container_name: bun-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped