name: CI/CD to Kubernetes (Bun)

on:
  push:
    branches:
      - main 
  pull_request: 
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: alghaza/bata-bumi-api:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.31.0"

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_OPM }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl delete deployment --all -n opm
          kubectl delete service --all -n opm
          kubectl delete ingress --all -n opm
          kubectl apply -f k8s/deployment.yaml -n opm
          kubectl apply -f k8s/service.yaml -n opm
          kubectl apply -f k8s/ingress.yaml -n opm
