name: Deeploy Backend Bata Bumi

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Bun environment (untuk lint/test)
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 3: Install dependencies & run tests
      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      # Step 5: Login ke GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Push image ke registry
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
